name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - main

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # check validate commit script
      - name: Run validate commits script
        run: |
          chmod +x ./validate-commits.sh && ./validate-commits.sh
